### ISSUE TITLE
مشکل در محصولات تک صفحه ای

### ISSUE THREAD

**Issue by mahmoudtavallaei** [rezakarbasi/Digikala-Spider#1]
سلام کد وقتی اجرا می شود نظرات محصولاتی که یک صفحه اند(یعنی در قسمت نظرات فقط یک صفحه نظر دارند) در فایل csv ذخیره نمی شوند برای حل مشکل چکار باید کرد و چه تغییراتی باید در کد داد؟ با تشکر

**Comment by rezakarbasi** [comment]
> سلام کد وقتی اجرا می شود نظرات محصولاتی که یک صفحه اند(یعنی در قسمت نظرات فقط یک صفحه نظر دارند) در فایل csv ذخیره نمی شوند برای حل مشکل چکار باید کرد و چه تغییراتی باید در کد داد؟ با تشکر

سلام
چون فارسی تایپ کردید ، یه مقدار بد دیده میشه سوالتون
منظورتون اینه که اگر نظرات برای یه محصول کلا یه صفحه باشه ، چکار باید کرد؟

**Comment by mahmoudtavallaei** [comment]
بله دقیقا یعنی با همین برنامه بشه هم نظرات چند صفحه ای و تک صفحه ای رو استخراج کرد

**Comment by rezakarbasi** [comment]
> بله دقیقا یعنی با همین برنامه بشه هم نظرات چند صفحه ای و تک صفحه ای رو استخراج کرد

**متن رو با اینتر های زیاد زدم که مشکل راست چین چپ چین گیتاب که باعث میشه متن فارسی به خوبی خونده نشه ، حل شه**


در تابع 
crawl_a_page
یک ورودی هست به نام 
endPage
با  مقدار دهی این پارامتر ، میشه که تعداد صفحه نظرات رو بهش داد

اما اول مطمئن بشید که کد برای حالتی که خودم نوشتم کار میکنه ، بعد سراغ این کار برید . چون من مدت ها درگیر این بودم که 
webdriver 
مربوط به گوگل کروم کار نمیکرد و مشکل داشت . و فکر میکردم که مشکل از یه جا دیگه س .

**Comment by mahmoudtavallaei** [comment]
ممنون برای راهنمایی
